---
- name: Setup AWS Infrastructure with Ansible
  hosts: localhost
  gather_facts: false
  vars_files:  #suppose if you don't want any variable file, you can directly hardcode it
    - /path/to/secrets.yml
    - /path/to/var.yml

#These ansible task will help us to create vpc, ec2 instance and s3 bucket with versioning enabled.
  tasks:
    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: "vpcUsingAnsible"
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_key }}"
        cidr_block: "{{ vpc_cidr_block }}"
        region: "{{ region }}"
      register: my_vpc

    - name: Create subnet
      amazon.aws.ec2_vpc_subnet:
        name: ""
        vpc_id: "{{ my_vpc.vpc.id }}"
        cidr: "{{ subnet_cidr_block }}"
        region: "{{ region }}"
      register: my_subnet

    - name: Create security group
      amazon.aws.ec2_security_group:
        name: "securitygroupusingansible"
        description: "My security group"
        vpc_id: "{{ my_vpc.vpc.id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            ports: "{{ security_group_port }}"
            cidr_ip: "{{ security_group_cidr_inbound }}"
        rules_egress:
          - proto: all
            cidr_ip: "{{ security_group_cidr_outbound }}"
      register: security_group

#Creating instance with ubuntu as a base image
    - name: Create EC2 instance
      amazon.aws.ec2_instance:
        name: "ec2UsingAnsible"
        aws_access_key_id: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: ansibleKey
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        wait: yes
        region: "{{ region }}"
        vpc_subnet_id: "{{ my_subnet.subnet.id }}"
        security_group: "{{ security_group.group_id }}"

    - name: Create S3 bucket with versioning
      amazon.aws.s3_bucket:
        name: "your-unique-name-bucket-name"
        state: present
        versioning: true
        region: "{{ region }}"

#Upload the object to the S3 bucket 
    - name: Upload object to S3
      amazon.aws.aws_s3:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_key }}"
        bucket: "your-unique-name-bucket-name"
        mode: put
        object: "file.png"
        src: "/path/to/file.png"
