- name: Create EC2 and VPC for aws resources
  hosts: localhost
  gather_facts: false
  vars_files:
    - secrets.yml
    - var.yml
  
  tasks:
    - name: Create EC2
      amazon.aws.ec2_instance:
        name: "ec2UsingAnsible"
        aws_access_key_id: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: ansibleKey
        instance_type: "{{ instance_type }}"
        image: "{{ ami_id }}"
        wait: yes
        region: "{{ region }}"

    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: "vpcUsingAnsible"
        cidr_block: "{{ vpc_cidr_block }}"
        region: "{{ region }}"
      register: my_vpc
    
    - name: Output VPC
      debug:
        msg: "The vpc id is {{ my_vpc.vpc.id }}"

    - name: Create subnet
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{ my_vpc.vpc.id }}"
        cidr: "{{ subnet_cidr_block }}"
        region: "{{ region }}"
      register: my_subnet

    - name: Output Subnet Id
      debug:
        msg: "The subnet id is {{ my_subnet.subnet.id }}"

    - name: Create security group
      amazon.aws.ec2_security_group:
        name: "securitygroupusingansible"
        description: "My security group"
        vpc_id: "{{ my_vpc.vpc.id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            ports: "{{ security_group_port }}"
            cidr_ip: "{{ security_group_cidr_inbound }}"
        rules_egress:
          - proto: all
            cidr_ip: "{{ security_group_cidr_outbound }}"
      register: security_group

    - name: Create S3 bucket with versioning
      amazon.aws.s3_bucket:
        name: "bucket-using-ansible-dev"
        state: present
        versioning: true
        region: "{{ region }}"

    - name: Upload objects in bucket
      amazon.aws.aws_s3:
        bucket: bucket-using-ansible-dev
        src: /home/ubuntu/ansible_ss.png
        mode: put